### ISSUE TITLE
Are you open to contributions?

### ISSUE THREAD

**Issue by CharlesGaydon** [rupak-118/AI-papers#1]
Hi Rupak
Really like this small selection of fundamental papers on the deep learning framework.
I see that last activity on this repo is >3y ago. Did you manage to work on the second part at some point? I will probably go through all listed articles, and I was wondering how I could contribute to the serie if I ever makes such summaries on my side. Co-authoring a second medium article is an idea I was considering. What do you think?

**Comment by Gr8ayu** [comment]
That would be really helpful. Also you can fork the repo and add your content and mention link to your repo in issue or pull request.

**Comment by rupak-118** [comment]
Sure, @CharlesGaydon .
I'll really appreciate contributions and collaborations on this blog series/repo. Let's connect on [LinkedIn](https://www.linkedin.com/in/rupak-thakur/) or mail to take this forward.

You can also fork the repo and add your content or if you want to add to this repo, you can raise a PR.

**Comment by CharlesGaydon** [comment]
Glad to hear that. You'll hear from me if I decide to go further with this idea in the next weeks. I'll have to go through a couple of the papers first, maybe try to redact a first summary, and go from there (if I find the time 🙃)!

**Comment by rupak-118** [comment]
Sure, Charles. Let me know.
